#!/bin/bash

#SBATCH -J cd-PET-sat
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem 4000M
#SBATCH -t 10:50:00
#SBATCH --gres=gpu:1
#SBATCH --exclude=gpua403,gpua412,gpua407,gpua408,gpua802


#SBATCH --partition=tier2_gpu



#SBATCH --account=aristeidis_sotiras

quota -s
